name: maximize
favicon: null
layout_spectrum: 0
typography_spectrum: 0.86213
title: Accelerating business growth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#58595b'
    - '#f69b2f'
    - '#ee632e'
    - '#cececf'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
